Adding HangFire artifact creation to azure pipeline
folkehelseinstituttet/Fhi.Smittestopp.Backend pull request #10
Opened 2020-11-24 18:27 UTC by martnc

Adding artifacts for HangFire pipeline

2020-11-26 07:23 UTC, matishadow requested changes

2020-11-26 07:23 UTC, matishadow commented on azure-pipelines.yml
> +# this uploads API as an artifact
Could you start this comment with Uppercase letter i.e. `This` so it's consistent with other comments?

2020-11-26 07:23 UTC, matishadow commented on azure-pipelines.yml
>  # execute on all branches
Could you start this comment with Uppercase letter i.e. `execute` so it's consistent with other comments?

2020-11-26 07:23 UTC, matishadow commented on azure-pipelines.yml
> +#Create the deploy package for HangFire
Could you add space between `#` and `Create` so it's consistent with other comments?

2020-11-26 16:36 UTC, flamaniac approved these changes

2020-11-27 10:09 UTC, matishadow approved these changes

2020-11-27 11:38 UTC, martnc commented
Updating azure pipeline to create zip files for both api and jobs.

2020-11-27 11:38 UTC, merged